In [1]:
import numpy as np

In [2]:
matchPenalty = 2
mismatchPenalty = -1
gapPenalty = -1

In [3]:
dnaSeq1 = "ATCAGAGTA" 
dnaSeq2 = "TTCAGTA"

In [4]:
rows = len(dnaSeq1) + 1
cols = len(dnaSeq2) + 1

In [5]:
dpMatrix = np.zeros((rows, cols), dtype = np.int)
dpMatrix.shape

(6, 5)

In [6]:
def printMatrix():
    for i in range(rows):
        for j in range(cols):
            print(dpMatrix[i][j], end = " ")
        print()

In [7]:
for i in range(rows):
    dpMatrix[i][0] = -1 * i
for j in range(cols):
    dpMatrix[0][j] = -1 * j 

In [8]:
printMatrix()

0 -1 -2 -3 -4 
-1 0 0 0 0 
-2 0 0 0 0 
-3 0 0 0 0 
-4 0 0 0 0 
-5 0 0 0 0 


In [9]:
def globalAlignment(rows, cols, seq1, seq2):
    for i in range(1, rows):
        for j in range(1, cols):
            if seq1[i-1] == seq2[j-1]:
                dpMatrix[i][j] = dpMatrix[i-1][j-1] + matchPenalty
            else:
                dpMatrix[i][j] = max(dpMatrix[i-1][j-1] + mismatchPenalty, dpMatrix[i-1][j] + gapPenalty, dpMatrix[i][j-1] + gapPenalty)

In [10]:
globalAlignment(rows, cols, dnaSeq1, dnaSeq2)

In [11]:
printMatrix()

0 -1 -2 -3 -4 
-1 2 1 0 -1 
-2 1 4 3 2 
-3 0 3 3 2 
-4 -1 2 2 2 
-5 -2 1 1 4 


In [12]:
len(dnaSeq1)

5

In [13]:
def localAlignment(rows, cols, seq1, seq2):
    for i in range(0, rows):
        for j in range(0, cols):
            if i == 0 or j == 0:
                dpMatrix[i][j] = 0
            elif seq1[i-1] == seq2[j-1]:
                dpMatrix[i][j] = dpMatrix[i-1][j-1] + matchPenalty
            else:
                dpMatrix[i][j] = max(0, dpMatrix[i-1][j-1] + mismatchPenalty, dpMatrix[i-1][j] + gapPenalty, dpMatrix[i][j-1] + gapPenalty)

In [14]:
# localAlignment(rows, cols, dnaSeq1, dnaSeq2)

In [15]:
printMatrix()

0 -1 -2 -3 -4 
-1 2 1 0 -1 
-2 1 4 3 2 
-3 0 3 3 2 
-4 -1 2 2 2 
-5 -2 1 1 4 


In [16]:
visited = np.zeros((rows, cols), dtype=np.int)

In [17]:
printMatrix()

0 -1 -2 -3 -4 
-1 2 1 0 -1 
-2 1 4 3 2 
-3 0 3 3 2 
-4 -1 2 2 2 
-5 -2 1 1 4 


In [18]:
print(visited)
print(visited.shape)
printMatrix()

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(6, 5)
0 -1 -2 -3 -4 
-1 2 1 0 -1 
-2 1 4 3 2 
-3 0 3 3 2 
-4 -1 2 2 2 
-5 -2 1 1 4 


In [19]:
def generateSequences(i, j, seq1, seq2, ans1, ans2):
    if i == 0 and j == 0:
        ans1 = ans1[::-1]
        ans2 = ans2[::-1]
        print(ans1)
        print(ans2)
        print()
        return
    elif i < 0 or j < 0 or visited[i][j] == 1:
    # if i<0 or j<0:
        return
    visited[i][j] = 1
    flag = 0
    if seq1[i-1] == seq2[j-1]:
        flag = 1
        generateSequences(i-1, j-1, seq1, seq2, ans1 + seq1[i-1], ans2 + seq2[j-1])
        # generateSequences(i-1, j-1, seq1, seq2, ans + str(dpMatrix[i][j]))
    # else:
    if dpMatrix[i][j] == dpMatrix[i-1][j-1] + mismatchPenalty:
        flag = 1
        # print(1)
        # generateSequences(i-1, j-1, seq1, seq2, ans + seq1[i-1])
        generateSequences(i-1, j-1, seq1, seq2, ans1 + seq1[i-1], ans2 + seq2[j-1])
        # generateSequences(i-1, j-1, seq1, seq2, ans + str(dpMatrix[i-1][j-1]))
        # generateSequences(i-1, j-1, seq1, seq2, ans + str(dpMatrix[i-1][j-1]))
    if dpMatrix[i][j] == dpMatrix[i-1][j] + gapPenalty:
        flag = 1
        # print(2)
        # generateSequences(i-1, j, seq1, seq2, ans1 + '-', ans2 + seq2[j-1])
        generateSequences(i-1, j, seq1, seq2, ans1 + seq1[i-1], ans2 + '-')
        # return
        # generateSequences(i-1, j, seq1, seq2, ans + '-')
        # generateSequences(i-1, j, seq1, seq2, ans + str(dpMatrix[i-1][j]))
    if dpMatrix[i][j] == dpMatrix[i][j-1] + gapPenalty:
        flag = 1
        # print(3)
        # generateSequences(i, j-1, seq1, seq2, ans1 + seq1[i-1], ans2 + '-')
        generateSequences(i, j-1, seq1, seq2, ans1 + '-', ans2 + seq2[j-1])
        # return
        # generateSequences(i-1, j, seq1, seq2, ans + '-')
        # generateSequences(i-1, j, seq1, seq2, ans + str(dpMatrix[i][j-1]))
    if flag == 0:
        generateSequences(i-1, j-1, seq1, seq2, ans1 + '-', ans2 + '-')
    visited[i][j] = 0

In [20]:
generateSequences(rows-1, cols-1, dnaSeq1, dnaSeq2, "", "")

ATTAC
A-TGC

ATTAC
AT-GC

ATTAC
ATG-C



In [21]:
matchPenalty = 2
mismatchPenalty = -3
gapPenalty = -2

In [22]:
globalAlignment(rows, cols, dnaSeq1, dnaSeq2)

In [23]:
printMatrix()

0 -1 -2 -3 -4 
-1 2 0 -2 -4 
-2 0 4 2 0 
-3 -2 2 1 -1 
-4 -1 0 -1 -2 
-5 -3 -2 -3 1 


In [24]:
generateSequences(rows-1, cols-1, dnaSeq1, dnaSeq2, "", "")

ATTAC
A-TGC

ATTAC
AT-GC

ATTAC
ATG-C

